services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.5
    container_name: elasticsearch
    hostname: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - bootstrap.memory_lock=true
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk
    mem_limit: 4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL","curl -fs http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.5
    container_name: kibana
    hostname: kibana
    restart: unless-stopped
    environment:
      - SERVER_PUBLICBASEURL=http://${PUBLIC_IP}:5601
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${KIBANA_ENCRYPTION_KEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${KIBANA_REPORTING_ENCRYPTION_KEY}
      - XPACK_SECURITY_ENCRYPTIONKEY=${KIBANA_SECURITY_ENCRYPTION_KEY}
      - TELEMETRY_OPTIN=false
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      elasticsearch:
        condition: service_healthy

  syslogng:
    image: balabit/syslog-ng:4.10.1
    container_name: syslog-ng
    restart: unless-stopped
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "514:514/udp"   # syslog UDP
      - "601:601"       # syslog TCP
    volumes:
      - ./syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
      - ./syslog-ng/state:/var/lib/syslog-ng
    networks:
      - elk
    read_only: true
    tmpfs:
      - /run/syslog-ng
      - /tmp
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  esdata:

networks:
  elk:
